src/dnlib.netstandard.csproj
Assembly signing is only supported on Windows with msbuild.
doesn't build on Linux with signing.
`dotnet build dnlib.netstandard.csproj` output
`CSC : error CS7027: Error signing output with public key from file '../dnlib.snk' -- Assembly signing not supported. [.../dnlib/src/dnlib.netstandard.csproj]`
=> Assembly Signing is not supported.

src/dnlib.netstandard.csproj
This change makes it so that the dnlib.netstandard.csproj file produces both .NET 3.5 and .NET Standard 2.0 binaries, and technically makes the original csproj obsolete (you need VS2017 for C# 7.2 anyway). This change also allows you to easily create a NuGet package on build that includes both versions using this csproj.
See issue #177. Also note that this isn't the Client version of .NET 3.5.
To build the .NET Standard version with .NET Core, use `dotnet build dnlib.netstandard.csproj -f netstandard2.0` now instead of `dotnet build dnlib.netstandard.csproj`.
=> Target both .NET Fx 3.5 and .NET Std 2.0 in dnlib.netstandard.csproj (closes #177)

src/DotNet/Importer.cs, src/DotNet/Pdb/WindowsPdb/WindowsPdbWriter.cs
I'm writing assembly processing library backed by dnlib and suggest a simple improvement to the dnlib.DotNet.Importer for the cases when the imported entity references renamed types in the target module. For example, type A has been imported into target assembly as A_1. 
Now, when processing a reference to A, Importer needs a way to remap the reference to A_1.
=> remap types in dnlib.DotNet.Importer

src/DotNet/AssemblyResolver.cs
The `dnlib.DotNet.AssemblyResolver` class has a new method called `GetCachedAssemblies` that allows access to the list of assemblies that are currently cached in the resolver.
=> GetCachedAssemblies function in AssemblyResolver

README.md, src/DotNet/Writer/ImportDirectory.cs
This PR adds the ability to overwrite the dll name being used/imported in `ImportDirectory`.
The purpose/use case for this is that .NET core libraries still have "mscoree.dll" in that section but to enable the DLLExport scenario for .NET core we have to use something different to be able to inject our own host/runtime resolution logic.
I use this technique to replace "mscoree.dll" with "ijwhost.dll". I guess the normal compile of .NET core will, sooner or later, also replace "mscoree.dll" in that place with something else.
=> Allow overwriting of the dll name which should be imported

src/DotNet/ICodedToken.cs, src/DotNet/TypeSig.cs
`MethodDef.Parameters` include a possible hidden 'this' parameter, `MethodDef.ParamDefs` don't include the hidden 'this' parameter, but it's possible not present.
Closes https://github.com/0xd4d/dnlib/issues/326
=> Add more extension methods

src/DotNet/Importer.cs, src/DotNet/ReflectionExtensions.cs, src/DotNet/SigComparer.cs
No need to unescape Type.Namespace.
This PR can fix #370
=> Unescape Type.Name & Type.FullName, fix #370

src/DotNet/Writer/Metadata.cs
Guess what I found out:
ResolutionScope now actually can be null/0 in .NET 5 reference assemblies, so the solution is to not throw an error and just return 0.
If you want to see this at work just build the attached project and try to rewrite the reference assembly (the one in the /ref subfolder) with this module, it will fail with error message "dnlib.DotNet.Writer.ModuleWriterException: ResolutionScope is null" though everything would be correct if we just return 0 (which is, after all, also what was read in).
I don't know if other properties of MetaData could be affected too, but that's what we experienced so far.
[TestProject.zip](https://github.com/0xd4d/dnlib/files/6799054/TestProject.zip)
Thanks so much for unarchiving the repository for this Pull Request! :)
=> ResolutionScope now actually can be null/0 in .NET 5 reference assemblies

src/DotNet/Writer/ModuleWriterBase.cs, src/DotNet/Writer/TablesHeap.cs
Also allows for the user to specify the value.
Can be used to bypass an anti-tampering check in which the obfuscator writes a different value than `1` and then checks at runtime if it is what it wrote.
=> Preserve Log2Rid value when rewriting a module.

src/DotNet/MemberFinder.cs
The value of a CAArgument was not analyzed which could cause incomplete results.
=> Improve CAArgument analysis in MemberFinder

src/DotNet/ModuleDefMD.cs, src/DotNet/ModuleLoader.cs, src/DotNet/Resource.cs, src/DotNet/Writer/Metadata.cs
Add support for reading and writing Custom Attributes and Custom Debug Infos for manifest resources.
=> CA and CDI support for manifest resources

src/DotNet/Resources/ResourceReader.cs
Version 1 resources should now be read properly. They are rewritten as version 2 when `ResourceWriter` is used. This code was based on the code in the `ResourceReader` class in `mscorlib` for .NET 2.0. I'm unaware of a way to produce these version 1 resources so I was not able to test this code but since it is pretty much 1:1 to the official implementation I think it's ok.
=> Add support for reading V1 resources

src/DotNet/Importer.cs
Add ImporterOptions.TryToUseExistingAssemblyRefs option to use already existing AssemblyRefs whenever possible
if .net 2.0 3.5 assembly is loaded in .net 4.x runtime, and we use importer to import something, that will cause both v2.0 reference assemblies and v4.0 reference assemblies appear in AssemblyRef table in saved assembly
=> Add ImporterOptions.TryToUseExistingAssemblyRefs option

src/DotNet/TypeHelper.cs
TypeSpec.ContainsGenericParameter should be handled in the same way with MethodSpec.ContainsGenericParameter.
The following code will let debugger break at CheckMethodSpec().
TypeHelper.ContainsGenericParameter(MethodSpec) should not always return true.
``` cs
using System.Diagnostics;
using dnlib.DotNet;
class Program {
static void Main() {
var module = ModuleDefMD.Load("dnlib.dll");
CheckTypeSpec(module);
CheckMethodSpec(module);
{
uint rid = 1;
MethodSpec ms;
while ((ms = module.ResolveMethodSpec(rid++)) is not null) {
}
}
{
uint rid = 1;
MethodDef md;
while ((md = module.ResolveMethod(rid++)) is not null) {
if (!md.HasBody)
continue;
foreach (var instr in md.Body.Instructions) {
if (instr.Operand is MethodSpec ms && ms.GenericInstMethodSig.ContainsGenericParameter)
Debugger.Break();
} …
```
=> Fixes TypeHelper.ContainsGenericParameter(MethodSpec)

src/DotNet/Importer.cs
Obfuscator may rename many methods/fields into same name then TryResolveMethod/TryResolveField will return inconsistent method/field.
Previous PR contains some problems and I fixed it. In previous PR you mentioned 'privatescope' visibility. I check some documents and find it is visible in the same module and can't be referenced in MemberRef table. I think these code won't get error when encountering 'privatescope' visibility. Should it be handled specially?
=> Improve Importer TryToUseMethodDefs and TryToUseFieldDefs options 2

src/DotNet/CustomAttributeReader.cs, src/DotNet/MD/BlobStream.cs, src/DotNet/SignatureReader.cs
=> Validate data in case allocate too many memory, fix #442

src/DotNet/Importer.cs, src/DotNet/ReflectionExtensions.cs
Linked issue: https://github.com/0xd4d/dnlib/issues/445
Test code:
``` cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using dnlib.DotNet;
using dnlib.DotNet.MD;
static class Program {
static readonly SigComparer FieldComparer = new(SigComparerOptions.DontCompareTypeScope | SigComparerOptions.CompareMethodFieldDeclaringType);
static readonly SigComparer MethodComparer = new(SigComparerOptions.DontCompareTypeScope | SigComparerOptions.CompareMethodFieldDeclaringType);
static void Main() {
Test(typeof(Program).Module);
Test(typeof(ModuleDef).Module);
Console.WriteLine("Pass");
Console.ReadKey(true);
}
static void Test(Module module) {
using var moduleDef = ModuleDefMD.Load(module, ModuleDef.CreateModuleContext());
var …
```
=> Fix 'Importer.Import(FieldInfo)' and 'Importer.ImportDeclaringType(Type)'

src/DotNet/SigComparer.cs
1.
Fix https://github.com/0xd4d/dnlib/issues/427
In code:
``` cs
static void Test<T>(Dictionary<T, T> dict) { string.Concat(dict); }
```
MethodSig of 'string.Concat' is 'string (IEnumerable<KeyPairValue<T, T>>)' and dnlib will repeat substitute one of 'T' in 'KeyPairValue<T, T>' with ''KeyPairValue<T, T>'' itself, so there is an infinite loop. I add a parameter to disable substituting when get hash code for 'GenericInstSig.GenericArguments'.
2.
About deleted code:
``` cs
if (SubstituteGenericParameters) {
InitializeGenericArguments();
genericArguments.PushTypeArgs(gia.GenericArguments);
hash += GetHashCode(gia.GenericType);
genericArguments.PopTypeArgs();
}
```
GenericType is always TypeDef or TypeRef so it makes no sense to substitute generic parameters.
=> Fix infinite loop in SigComparer.GetHashCode(TypeSig)

src/DotNet/Importer.cs, src/DotNet/SigComparer.cs
1. Fix Importer and SigComparer‘s handling of generic when must treat generic type definition as generic instantiation type.
2. Mark Importer.ImportDeclaringType(Type) as obsolete.
Closes https://github.com/0xd4d/dnlib/issues/462, Closes https://github.com/0xd4d/dnlib/issues/463, Closes https://github.com/0xd4d/dnlib/issues/464, Closes https://github.com/0xd4d/dnlib/issues/465
Test code (run all gac assemblies and built-in test cases, include MemberRef table, Field table, Method table, MethodSpec table, Property table, Event table):
``` cs
public static class Program {
static IEnumerable<string> GetAssemblyPaths() {
var gacBasePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows), @"Microsoft.NET\assembly");
var gacPaths = new[] { Path.Combine(gacBasePath, …
```
=> Fix Importer and SigComparer‘s handling of generic when must treat generic type definition as generic instantiation type.

src/DotNet/SigComparer.cs
Fix #468
Also fix similar problems that existed before.
Includes:
Equals(IMethod, MethodBase)
Equals(IField, FieldInfo)
GetHashCode(IMethod)
GetHashCode(IField)
GetHashCode(MethodBase)
GetHashCode(FieldInfo)
Test code:
same as pr #466 but delete 'SigComparerOptions.CompareMethodFieldDeclaringType'
=> Don't substitute type generic arguments when don't compare declaring type.

src/DotNet/Emit/DynamicMethodBodyReader.cs
* Added support for reading `InitLocals` property and use the value in `GetMethod` and `RestoreMethod`.
* Set `MaxStack` property in `RestoreMethod`.
=> Improvements to `DynamicMethodBodyReader`

src/DotNet/Pdb/CustomDebugInfoGuids.cs, src/DotNet/Pdb/Dss/SymbolDocumentImpl.cs, src/DotNet/Pdb/Managed/DbiDocument.cs, src/DotNet/Pdb/PdbCustomDebugInfo.cs, src/DotNet/Pdb/PdbDocument.cs, src/DotNet/Pdb/PdbState.cs, src/DotNet/Pdb/Portable/PortablePdbCustomDebugInfoReader.cs, src/DotNet/Pdb/Portable/PortablePdbCustomDebugInfoWriter.cs, src/DotNet/Pdb/Portable/PortablePdbReader.cs, src/DotNet/Pdb/Portable/SymbolDocumentImpl.cs, src/DotNet/Pdb/Symbols/SymbolDocument.cs, src/DotNet/Writer/Metadata.cs
Add support for the following CustomDebugInfos:
* TypeDefinitionDocuments  (fixes #430)
* EncStateMachineStateMap
=> Add support for new Roslyn CustomDebugInfo

src/DotNet/Emit/DynamicMethodBodyReader.cs, src/DotNet/Emit/MethodTableToTypeConverter.cs
.NET 8 changed the following:
* `DynamicMethod.m_resolver` ->`DynamicMethod._resolver` - This field is used by `DynamicMethodBodyReader` to retrieve the `DynamicResolver` instance.
* `ILGnerator` became an abstract class and the actual implementation was moved to `RuntimeILGenerator` - `MethodTableToTypeConverter` accesses a private field in the ILGenerator implementation and needed to be updated to check `RuntimeILGenerator`
I've also added support for `DynamicMethodBodyReader` to consume dynamic methods created from a `DynamicILInfo` which were not jet used as part of an invocation or a delegate.
=> Add support for .NET 8.0 and `DynamicILInfo` to `DynamicMethodBodyReader`

src/DotNet/WinMDHelpers.cs
The rationale for the `WinMDHelpers` change can be found in: https://github.com/0xd4d/dnlib/issues/510
=> Expose `WinMDHelpers` class

src/DotNet/Resources/BuiltInResourceData.cs, src/DotNet/Resources/IResourceData.cs, src/DotNet/Resources/ResourceBinaryWriter.cs, src/DotNet/Resources/ResourceDataFactory.cs, src/DotNet/Resources/ResourceElementSet.cs, src/DotNet/Resources/ResourceReader.cs, src/DotNet/Resources/ResourceReaderType.cs, src/DotNet/Resources/ResourceWriter.cs, src/DotNet/Resources/UserResourceData.cs
* Updated code in `CheckReaders` to match the actual meaning of the fields. The implementation now matches the one in the runtime.
* Added several new members to allow creating of more customized resource sets.
* Added support for the `DeserializingResourceReader` class introduced in .NET 5 and now in the `System.Resources.Extensions` package.
The changes should be source and binary compatible with the previous dnlib version. This limited the support I could provide for this new resource reader which specifies additional information on how to deserialize objects with different serialization kinds for the `UserType` type code.
See:
https://github.com/dotnet/dotnet/blob/95703b57cf3dfaa79f054d277551a809d4f7696a/src/runtime/src/libraries/System.Resources.Extensions/src/System/Resources/Extensi …
=> Add rudimentary support for `DeserializingResourceReader`

src/DotNet/ICodedToken.cs
Fix https://github.com/0xd4d/dnlib/issues/471
=> Don't create wrong TypeSig for TypeDef

src/DotNet/AssemblyResolver.cs, src/DotNet/Emit/MethodTableToTypeConverter.cs, src/DotNet/ImplMap.cs, src/DotNet/Importer.cs, src/DotNet/ModuleDefMD.cs, src/DotNet/Pdb/Dss/SymbolReaderWriterFactory.cs, src/DotNet/Pdb/Dss/SymbolWriterImpl.cs, src/DotNet/Pdb/Managed/DbiModule.cs, src/DotNet/Pdb/Managed/DbiScope.cs, src/DotNet/Pdb/Managed/PdbException.cs, src/DotNet/Pdb/Managed/PdbReader.cs, src/DotNet/Pdb/PdbConstant.cs, src/DotNet/Pdb/Portable/ImportDefinitionKindUtils.cs, src/DotNet/Pdb/Portable/ImportScopeBlobReader.cs, src/DotNet/Pdb/Portable/LocalConstantSigBlobReader.cs, src/DotNet/Pdb/Portable/PortablePdbCustomDebugInfoReader.cs, src/DotNet/Pdb/Portable/PortablePdbReader.cs, src/DotNet/Pdb/SymbolReaderFactory.cs, src/DotNet/Pdb/WindowsPdb/PdbCustomDebugInfoReader.cs, src/DotNet/Resources/ResourceDataFactory.cs, src/DotNet/Resources/ResourceWriter.cs, src/DotNet/Writer/ModuleWriterBase.cs, src/IO/DataReader.cs, src/IO/DataReaderFactoryFactory.cs, src/PE/ProcessorArchUtils.cs, src/dnlib.csproj
Fixes https://github.com/0xd4d/dnlib/issues/514
This PR adds support `net6.0` target for `dnlib`. The rationale for this change was discussed in the aforementioned issue and updates the NuGet packages used by `dnlib` to the latest available versions.
I've also gone ahead and replaced most of the usages of string concatenation and replaced it with string interpolation. This allows Roslyn to better take advantage of the faster string API's available in .NET 6. Some code changes were also necessary to resolve warnings regarding obsolete members and platform compatibility of the unmanaged Windows PDB support. A few NRE's which were picked up by code analysis were also fixed!
=> Add additional net6.0 target framework

src/DotNet/Importer.cs
This PR resolve following issues:
1. Fix inconsistent type like this which for method/field:
#443 https://github.com/0xd4d/dnlib/commit/8ed982fc0760adb7597ffbf2f1cecfcd97d819a3
2. `TryToUseTypeDefs` can work also without creating an `AssemblyResolver` (`NullResolver` by default)
=> Improve Importer TryToUseTypeDefs

src/DotNet/SigComparer.cs
=> Compare reference only for MemberDefs if they are from the same module

src/DotNet/Emit/Instruction.cs
`ParameterList` created a `GenericInstSig` if declaring type is generic, while `Instruction.GetArgumentType` did not.
https://github.com/0xd4d/dnlib/blob/8558fa74e2382fe8acfecbbb04e3a48e07e01953/src/DotNet/ParameterList.cs#L122-L138
https://github.com/0xd4d/dnlib/blob/8558fa74e2382fe8acfecbbb04e3a48e07e01953/src/DotNet/Emit/Instruction.cs#L747-L748
if `declaringType` is `TypeSpec` we trust the user to provide the proper instantiated type!
=> Make `Instruction.GetArgumentType` consistent with `ParameterList`

src/DotNet/AssemblyDef.cs, src/DotNet/AssemblyNameInfo.cs, src/DotNet/AssemblyRef.cs, src/DotNet/Emit/InstructionPrinter.cs, src/DotNet/ExportedType.cs, src/DotNet/FullNameFactory.cs, src/DotNet/TypeDef.cs, src/DotNet/TypeRef.cs, src/DotNet/Utils.cs, src/DotNet/Writer/CustomAttributeWriter.cs, src/DotNet/Writer/DeclSecurityWriter.cs
Implementation as described in #519 
Will add the assembly full name improvements after they are greenlit over at #519.
fixes #519 (For GitHub to properly link the PR to the issue :D)
=> Optimize type name computation

Examples/Example6.cs, src/DotNet/Utils.cs, src/DotNet/Writer/ArrayWriter.cs, src/DotNet/Writer/ByteArrayChunk.cs, src/DotNet/Writer/ChunkListBase.cs, src/DotNet/Writer/DataReaderChunk.cs, src/DotNet/Writer/DebugDirectory.cs, src/DotNet/Writer/HeapBase.cs, src/DotNet/Writer/IChunk.cs, src/DotNet/Writer/ImageCor20Header.cs, src/DotNet/Writer/ImportAddressTable.cs, src/DotNet/Writer/ImportDirectory.cs, src/DotNet/Writer/ManagedExportsWriter.cs, src/DotNet/Writer/Metadata.cs, src/DotNet/Writer/MetadataHeader.cs, src/DotNet/Writer/MethodBody.cs, src/DotNet/Writer/MethodBodyChunks.cs, src/DotNet/Writer/ModuleWriterBase.cs, src/DotNet/Writer/NetResources.cs, src/DotNet/Writer/PEHeaders.cs, src/DotNet/Writer/RelocDirectory.cs, src/DotNet/Writer/StartupStub.cs, src/DotNet/Writer/StrongNameSignature.cs, src/DotNet/Writer/TablesHeap.cs, src/DotNet/Writer/UniqueChunkList.cs, src/DotNet/Writer/Win32ResourcesChunk.cs
Current changes:
* Added `ArrayWriter.Position` setter (not really related to this PR but thought I would squeeze it in, makes consuming the class more pleasant)
* Added `IChunk.CalculateAlignement` method to calculate the required alignment of a specific chunk.
* Extended `ByteArrayChunk` constructor to accept required alignment.
Things left to do:
I've also been wondering if chunks like `StrongNameSignature` or `Win32ResourcesChunk` should define a `CalculateAlignment` which returns the default alignments used when adding them to their respective chunk lists to better reflect the alignment they necessitate to the user.
fixes #454
=> Align field initial value to match the Microsoft's ECMA augments

src/DotNet/SigComparer.cs
Due to the urgency of this issue and the need for a quick fix, I have opened another pull request as opposed to #524 to demonstrate an alternative fix.
Advantages of this PR over #524:
* Makes the `SigComparer` in the next release backward compatible with the previous 3.6 one.
* Fixed the issue by making reference comparisons opt-in.
* Has clearly defined behavior in the flags and does not make `SigComparer` flags depend on other flags which has the benefits of clearer behavior and less chance of potentially introducing bugs later down the line.
* Adds convenience properties for reference comparing member definitions.
If this PR is merged, we can close #524 and quickly release a hotfix version for 4.0.
@wtfsck @CreateAndInject
=> Resolve `SigComparer` regression introduced in 4.0

src/DotNet/Writer/TablesHeap.cs
Fixes https://github.com/0xd4d/dnlib/issues/530
The fix was implemented by adjusting the row counts passed into the `InitializeSizes` to fix a bug where the row counts were incorrect. The patch is heavily based on the code from `TablesStream`:
https://github.com/0xd4d/dnlib/blob/67396c0e5c3a8c27ac220aa5b3692fcf49f44ebf/src/DotNet/MD/TablesStream.cs#L254-L265
=> Fix incorrect column sizes when writing portable or embedded PDB files

src/DotNet/Writer/NativeModuleWriter.cs
When I saved a file, I got an invalid .NET file, since COR20 header signature is rewritten.
=> Check overlaps

src/DotNet/AssemblyResolver.cs
By the way, is there any issue in .editorconfig file? The code is always changed when formating (Ctrl + E, D)
=> Clean moduleSearchPaths

src/DotNet/GenericParam.cs, src/DotNet/GenericParamAttributes.cs
See:
https://github.com/dotnet/runtime/blob/main/docs/design/features/byreflike-generics.md
https://github.com/dotnet/runtime/issues/102671
https://github.com/dotnet/runtime/blob/9daa4b41eb9f157e79eaf05e2f7451c9c8f6dbdc/src/coreclr/inc/corhdr.h#L847
The code responsible for this flag appears to be in the main branch of the runtime already.
=> Add new `AllowByRefLike` generic parameter attribute

src/DotNet/Writer/Metadata.cs
fixes https://github.com/0xd4d/dnlib/issues/558
The algorithm suggested in the issue was adjusted to allow more than one nested type per exported type.
Something to consider:
The current algorithm does not dispose of the enumerators generated just like the method in https://github.com/0xd4d/dnlib/blob/4e0837cb0f4319ffbcdd1642d1973fce203b2177/src/DotNet/AllTypesHelper.cs#L14. This should be fine since list enumerators don't contain any logic in their `Dipose` method but this is something we'd probably need to add to both implementations for future-proofing and potential reuse. Perhaps we could also extract this traversal into an additional class for future use.
=> Sort `ExportedType` table when writing to comply with new ECMA Augments
